### ISSUE TITLE
Filter with relation

### ISSUE THREAD

**Issue by bertt** [gost/server#110]
Do we support these kind of filters (from the specs):

"Example Request 2: http://example.org/v1.0/Observations?$filter=Datastream/id eq ‘1’ returns all Observations whose Datastream’s id is 1."

http://docs.opengeospatial.org/is/15-078r6/15-078r6.html

**Comment by bertt** [comment]
must be something like: http://example.org/v1.0/Observations?$filter=Datastream/@iot-id eq ‘1’

**Comment by tebben** [comment]
http://example.org/v1.0/Observations?$filter=Datastream/id eq ‘1’ should be supported by the system. Datastream/id is already extracted by godata as FilterTokenNav, based on this information a subquery needs to be generated. I will look into this

**Comment by bertt** [comment]
this is not working:

give things with location.name == "Somewhere1"

```
$ curl http://localhost:8080/v1.0/Things?$filter=Locations/name eq ‘Somewhere1’

{
   "error": {
      "status": "Internal Server Error",
      "code": 500,
      "message": [
         "No matching token for ‘Somewhere1’"
      ]
   }
}
```

**Comment by tebben** [comment]
Related entities in a odata query is not yet supported (Locations/name) you are also using strange quotation marks. ‘Somewhere1’ instead of 'Somewhere1'

**Comment by tebben** [comment]
Pushed changes to support filter on relation in https://github.com/gost/server/commit/870699b2dd4b05923891b14d2458a9d29a5a7689 example request above works but filter on relation needs some more work to support different scenarios, for instance http://localhost:8080/v1.0/Things?$expand=Locations&$filter=Locations/name eq 'test location 2' returns incorrect data.

 http://localhost:8080/v1.0/Things?$filter=Locations/name eq 'Somewhere1'
```
{
   "value": []
}
```
 http://localhost:8080/v1.0/Things?$filter=Locations/name eq 'test location 2'
```
{
   "value": [
      {
         "@iot.id": 505,
         "@iot.selfLink": "http://localhost:8080/v1.0/Things(505)",
         "name": "thing name 2",
         "description": "thing 2",
         "properties": {
            "reference": "second"
         },
         "Locations@iot.navigationLink": "http://localhost:8080/v1.0/Things(505)/Locations",
         "Datastreams@iot.navigationLink": "http://localhost:8080/v1.0/Things(505)/Datastreams",
         "HistoricalLocations@iot.navigationLink": "http://localhost:8080/v1.0/Things(505)/HistoricalLocations"
      }
   ]
}
```

**Comment by tebben** [comment]
Described scenario in last commit seems to work now after changes to the QueryBuilder for other issues. Closing issue
