### ISSUE TITLE
Thing with multiple locations

### ISSUE THREAD

**Issue by bertt** [gost/server#125]
from the spec (http://docs.opengeospatial.org/is/15-078r6/15-078r6.html#26): "A Thing SHOULD have only one Location. However, in some complex use cases, a Thing MAY have more than one Location representations. In such case, the Thing MAY have more than one Locations. These Locations SHALL have different encodingTypes and the encodingTypes SHOULD be in different spaces (e.g., one encodingType in Geometrical space and one encodingType in Topological space)."

So I think posting **twice** the same location (with same encoding) to a thing should not be allowed?

What to do in case of a moving Thing?

http post localhost:8080/v1.0/Things(1)/Locations

{
    "name": "Somewhere2",
    "description": "my backyard",
    "encodingType": "application/vnd.geo+json",
    "location": {
        "type": "Point",
        "coordinates": [-117.123,
        54.123]
    }
} 

actual result: 201 created
expected result: 400?

**Comment by bertt** [comment]
what are those "complex use cases"?

**Comment by bertt** [comment]
testcase:
- post multiple location with samen encodingtype
- get location should return only the last location?

**Comment by bertt** [comment]
/things?expand=historicallocation/locations

**Comment by bertt** [comment]
questions:
- how to request actual location of thing?
- how to request trail of thing?

**Comment by tebben** [comment]
Example requests

Latest location of Thing 1
localhost:8080/v1.0/Things(1)/Locations

Thing 1 including latest location
localhost:8080/v1.0/Things(1)?$expand=Locations

Thing 1 location trail
localhost:8080/v1.0/Things(1)/HistoricalLocations?$expand=Locations

Thing 1 including location trail
http://localhost:8080/v1.0/Things(1)?$expand=HistoricalLocations/Locations

**Comment by bertt** [comment]
about actual location of thing:

issue is that GOST implementation allows multiple locations for a thing with same encodingtype, this is not allowed according to the spec.

So localhost:8080/v1.0/Things(1)/Locations gives a list of locations in this case. To know the actual location of the thing, should the client find the last element in this list of locations?

**Comment by bertt** [comment]
fix:

-  localhost:8080/v1.0/Things(1)/Locations should always return the last location of the thing instead of list of locations

**Comment by tebben** [comment]
Also when using $expand
localhost:8080/v1.0/Things?$expand=Locations
localhost:8080/v1.0/Datastreams?$expand=Thing/Locations
etc

**Comment by tebben** [comment]
Should be fixed now, changes need to be done when SensorThings specifies multiple encoding-types for locations.

**Comment by bertt** [comment]
did a test, now 1 location is return but it's always the first location, expecting to get the last added location

**Comment by tebben** [comment]
on $expand it worked but not when retrieving Location by Thing, there was a sorting problem because of the used coupling table between Location and Thing. It should be fixed now, tested both cases and tests and est-sta10 are running. 

Going to test now if this change has any performance impact since the query order changed a bit.

**Comment by bertt** [comment]
test manually + ets_sta10 succeeded, closing issue

**Comment by tebben** [comment]
Looks fast to me, maybe even faster.
