### ISSUE TITLE
$expand with separated inline query options does not work

### ISSUE THREAD

**Issue by tebben** [gost/server#129]
Multiple queries options divided by a semicolon do not work inside an expand: /v1.0/Things(1)?$expand=Datastreams/Observations($select=result;$top=1)

**Comment by bertt** [comment]
Actual reponse: 

```
{
error: {
status: "Internal Server Error",
code: 500,
message: [
"Mismatched parentheses in expand clause."
]
}
}
```

**Comment by tebben** [comment]
Should be fixed with commit: https://github.com/gost/server/commit/a5054aaf1dbe7f54749efd109365df77b8a851d5 
Semicolon in inline query resulted in incomplete url query values, solved by encoding ; to %3B in RawQuery, encoding the complete url first didn't work and resulted in other errors.

@bertt Please check and close

**Comment by bertt** [comment]
tested manually /v1.0/Things(1)?$expand=Datastreams/Observations($select=result;$top=1), gives now a Thing response with Datastream instead of 500 error
