### ISSUE TITLE
filter error 500 "column not exists"

### ISSUE THREAD

**Issue by joernahlers** [gost/server#132]
Hello,

when i try to filter some observations from the things i can use a request like this:
[](
"https://test.org/v1.0/Things?$filter=Datastreams/Observations/result gt 10")

but i get this response:

```
{
   "error": {
      "status": "Internal Server Error",
      "code": 500,
      "message": [
         "Error executing query pq: column "datastreams" does not exist"
      ]
   }
}
```

**Comment by tebben** [comment]
You are trying to filter on relation which is not yet supported: https://github.com/gost/server/issues/110 The request asks to retrieve all Things where a related datastream contains an observation where result is greater than 10, is this what you want, what's the scenario?

**Comment by joernahlers** [comment]
Yes this is exactly what i want. 
In the example request 4 at the section 9.3.3.5 $filter from the SensorThing specification is a good example:

http://example.org/v1.0/Things?$expand= Datastreams/Observations/FeatureOfInterest&$filter=Datastreams/Observations/FeatureOfInterest/id eq ‘FOI_1’ and Datastreams/Observations/resultTime ge 2010-06-01T00:00:00Z and Datastreams/Observations/resultTime le 2010-07-01T00:00:00Z returns Things that have any observations of a feature of interest with a unique identifier equals to ’FOI_1’ in June 2010.

**Comment by bertt** [comment]
yes the last query we've seen too (https://github.com/gost/server/issues/118) but it doesn't work yet

**Comment by tebben** [comment]
Request https://test.org/v1.0/Things?$filter=Datastreams/Observations/result gt 10 should work in latest version, however filtering on relation needs some more work for other cases. Closing this issue and continuing in https://github.com/gost/server/issues/110
