### ISSUE TITLE
docker file apt-get clean up

### ISSUE THREAD

**Issue by bertt** [gost/server#133]
add 'apt-get clean' after the 'apt-get update' (on same line) to keep image small

**Comment by tebben** [comment]
Dockerfile updated in commit https://github.com/gost/server/commit/4cf873b6b82100229fef11871ffdcdcaad410d59 :
- Removed apt-get update, looks like it's not needed
- Combined multiple layers
- Build output and config file to other path. 

Only won 10 MB with changes, basefile golang:latest is already 266 MB

config.yaml file can now easily changed by the user using a mountpoint.
