### ISSUE TITLE
refactor: move sensorthings.entities to separate repository

### ISSUE THREAD

**Issue by bertt** [gost/server#135]
we have duplicate code for sensorthings entities: 
- https://github.com/gost/sensorthings-cli/blob/master/sti/cmd/entities.go
- https://github.com/gost/server/blob/master/sensorthings/entities/entity.go

solution: move entities code to separate repository

work involved:
- create new repository
- move code 
- make gost/server dependent on new repository
- make gost/sensorthings-cli dependent on new repository
- test all the things

remarks:
- name: https://github.com/gost/core ?
- does the new repository need to have have dependency on gostErrors "github.com/gost/server/errors" or not? No dependency preferred (is only used once in https://github.com/gost/server/tree/master/sensorthings/entities).

**Comment by bertt** [comment]
created https://github.com/gost/core

**Comment by tebben** [comment]
dependencies removed from gost/server/sensorthings/entities ready for transfer to gost/core

**Comment by bertt** [comment]
entities copied to https://github.com/gost/core

**Comment by bertt** [comment]
entities code is removed from https://github.com/gost/server + dependency is added https://github.com/gost/server/commit/11906bf0c80f1cf707e56e21420961ef4c58f029

**Comment by bertt** [comment]
entities code removed from https://github.com/gost/sensorthings-cli + dependency is added https://github.com/gost/sensorthings-cli/commit/7ec1b29e786117474e2452e6b6e28aa38711aadd

**Comment by bertt** [comment]
todo: update connectors code too but thats a separate topic, closing for now
