### ISSUE TITLE
fix gocyclo warnings

### ISSUE THREAD

**Issue by bertt** [gost/server#137]
fix 5 files with gocyclo warnings:

- server/database/postgis/dbinfo.go
- server/configuration/environment.go
- server/sensorthings/rest/writer/writer.go
- server/database/postgis/querybuilder.go
- server/database/postgis/queryexecutor.go

see also https://goreportcard.com/report/github.com/gost/server

**Comment by tebben** [comment]
gocyclo depends on -over flag which is set to 15 for the report card, did some refactoring to pass 100% on the report card but querybuilder and queryexecutor can still use some more refactoring.
@bertt close issue?

**Comment by bertt** [comment]
ok let's close it, maybe create new issue for other refactoring
