### ISSUE TITLE
FeatureOfInterest self link gives 404

### ISSUE THREAD

**Issue by bertt** [gost/server#140]
sample:

request: https://gost.geodan.nl/v1.0/Observations(1993145)/FeatureOfInterest
response:
```
{
@iot.id: 153,
@iot.selfLink: "https://gost.geodan.nl/v1.0/FeatureOfInterest(153)",
name: "Amsterdam ArenA",
description: "Center of Amsterdam ArenA",
encodingType: "application/vnd.geo+json",
feature: {
coordinates: [
4.941964,
52.314371
],
type: "Point"
},
Observations@iot.navigationLink: "https://gost.geodan.nl/v1.0/FeatureOfInterest(153)/Observations"
}
```

Request: https://gost.geodan.nl/v1.0/FeatureOfInterest(153)
Response: 404

But: https://gost.geodan.nl/v1.0/FeaturesOfInterest(153) works?

**Comment by tebben** [comment]
Fixed in core: https://github.com/gost/core/commit/86b03f2e52f7b39f2a87ebf5e1a3e36d7e1a9c96 
run "dep ensure -update github.com/gost/core" to update to the latest version of gost core

**Comment by tebben** [comment]
Opened again for @bertt to test the fix first

**Comment by bertt** [comment]
tested manual and in ets-sta10, works allright now
