### ISSUE TITLE
The @iot.nextLink MUST NOT contain spaces

### ISSUE THREAD

**Issue by dglachs** [gost/server#143]
When querying entities with a **$filter statement** the result set has an invalid "@iot.nextLink" URI. Because the $filter statement is added urldecoded to the  "@iot.nextLink" 

sending 
`.../Datastreams?$filter=name+eq+%27name%27`
must not be returned in the "@iot.nextLink" as 
`.../Datastreams?$filter=name eq 'name'&$top=20&$skip=20`

**Comment by tebben** [comment]
Should be fixed now, can you test if it works for you and close the issue? Also the mentioned query in the referenced issue ?$filter=unitOfMeasurement/symbol eq '%25' looks to work correctly including nextlink.

**Comment by dglachs** [comment]
Great response time 👍 Thx!
