### ISSUE TITLE
Wrong formatting of object in Observation.result 

### ISSUE THREAD

**Issue by farshidtz** [gost/server#155]
Hi,

GOST accepts a JSON object in result but parses it as string and wrongly during retrieval.

Here is an example:
POST /v1.0/Datastreams(3)/Observations
```
{
  "result": {"x":"10","y":"20"}
}
```

Response body
```
{
   "@iot.id": 12223,
   "@iot.selfLink": "http://localhost/v1.0/Observations(12223)",
   "phenomenonTime": "2018-10-04T09:36:56.066Z",
   "result": {
      "x": "10",
      "y": "20"
   },
   "Datastream@iot.navigationLink": "http://localhost/v1.0/Observations(12223)/Datastream",
   "FeatureOfInterest@iot.navigationLink": "http://localhost/v1.0/Observations(12223)/FeatureOfInterest"
}
```

The above response is correct.

GET /v1.0/Observations(12223)
```
{
  "@iot.id": 12223,
  "@iot.selfLink": "http://localhost/v1.0/Observations(12223)",
  "phenomenonTime": "2018-10-04T09:36:56.066Z",
  "result": "{x: \"10\", \"y\": \"20\"}",
  "Datastream@iot.navigationLink": "http://localhost/v1.0/Observations(12223)/Datastream",
  "FeatureOfInterest@iot.navigationLink": "http://localhost/v1.0/Observations(12223)/FeatureOfInterest",
  "resultTime": null
}
```

But the GET response is wrong: "{x: \"10\", \"y\": \"20\"}"
Seems like GOST takes the result as string and removes the first two escaped strings: https://github.com/gost/server/blob/085b21972f9151b559059aa50f7c5ce48930602c/database/postgis/observation.go#L43

The response should be similar to the POST response: an object value for result.

FYI, SensorThings allows storing any type in result when `observationType` is OM_Observation: http://docs.opengeospatial.org/is/15-078r6/15-078r6.html#table_12

Thanks,

**Comment by tebben** [comment]
JSON got serialised 2 times resulting in escaped chars, the type of result is changed from interface to json.RawMessage in gost/core to prevent this from happening. All ets-sta10 tests seem to run fine after this change, problem should be fixed in latest docker file.

**Comment by farshidtz** [comment]
Thanks a lot. It is fixed now.
