### ISSUE TITLE
Initialising database for binary version of server

### ISSUE THREAD

**Issue by Dheeman1999** [gost/server#175]
When working with binary version of the server, valid endpoints give out 500 error saying postgresql has no schema v1 or database gost, is there a way to automatically initialize the database for binary version of the server or does it have to be done manually?

**Comment by bertt** [comment]
Hi, in the server there is no functionality to initialize the database. So first a database with valid schema has to be created, after that the server will work. 
Sql script for creatig database schema can be found at https://github.com/gost/gost-db/blob/master/gost_init_db.sql

**Comment by Dheeman1999** [comment]
@bertt Thanks so much for the clarification, closing the issue now
