### ISSUE TITLE
Strange behaviour when filtering on Thing-properties

### ISSUE THREAD

**Issue by derkod** [gost/server#176]
We have defined several properties under a Thing. Like this:
```
{
    "owner": "Luftdaten",
    "project": "Luftdaten",
    "knmicode": "knmi_06215",
    "nh3stadcode": null,
    "no2stadcode": "NL10445",
    "gemeentecode": "518",
    "nh3closecode": "NL10444",
    "nh3regiocode": "NL10444",
    "no2closecode": "NL10446",
    "no2regiocode": "NL10444",
    "pm10stadcode": "NL10445",
    "pm25stadcode": "NL01491",
    "pm10closecode": "NL10446",
    "pm10regiocode": "NL10444",
    "pm25closecode": "NL10404",
    "pm25regiocode": "NL10444"
}
```

It is possible to filter on all properties.
E.g. https://ontw.api-samenmeten.rivm.nl/v1.0/Things?$filter=properties/project%20eq%20%27Luftdaten%27 (unfortunately, this url is not available on the Internet yet. It is in development)
All properties are filter-able like this, except: gemeentecode
https://ontw.api-samenmeten.rivm.nl/v1.0/Things?$filter=properties/gemeentecode%20eq%20%27518%27
gives a Bad Gateway-error. And long message in the log. (Full message in file)

```
2020/07/07 06:22:19 http: panic serving 10.128.0.1:57850: runtime error: index out of range
goroutine 1123289 [running]:
net/http.(*conn).serve.func1(0xc00033a280)
      /usr/local/go/src/net/http/server.go:1746 +0xd0
panic(0x7cdb20, 0xb3f8a0)
      /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/gost/server/database/postgis.(*QueryBuilder).sortFilter(0xc0001d2040, 0xc000eb9548, 0xc000beeae0, 0xc000beeb40, 0xc000beeae0, 0xc00128a460
```
[gostapi-property-filter-error.txt](https://github.com/gost/server/files/4884232/gostapi-property-filter-error.txt)

The only difference in properties is that gemeentecode is a number. Will that cause the problem???

**Comment by bertt** [comment]
Hi, we could reproduce this behaviour, but its not the gemeentecode number. Turns out its a bug in the server, it occurs when the query is searching on a field name starting with one of the logical operators (eq, ne, gt, ge, lt, le, and, or, not, has). We will take it a look at it for next release. 

So as a workaround do not start the fieldnames with one of those logical operators.

**Comment by derkod** [comment]
Wow, thanks for this quick response. We will rename this particular fieldname.

**Comment by tebben** [comment]
Like Bert said, logical operators got extracted when they where found at the beginning of a string. I updated the regex in godata - filter_parser to match the logical operators better, the server now uses the updated version. 

When using the docker image geodan/gost:latest the bug should be solved.
