### ISSUE TITLE
Parse Observation Result to correct ObservationType

### ISSUE THREAD

**Issue by tebben** [gost/server#41]
Parse Observation Result to correct ObservationType.

ObservationType: "http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_Measurement" Result "18" should return 18 so nor parsing is needed in clients.

**Comment by bertt** [comment]
can you add sample?

**Comment by tebben** [comment]
Table 811 in the SensorThings spec states 
  - OM_Measurement = double
  - OM_CountObservation = integer
  - OM_Observation = Any
  - OM_ThruthObservation= boolean
  - OM_CategoryObservation = Uri

In my opinion it should not be possible that a client receives a datatype that is not expected, for instance when a Datastream.DataType is set to OM_Measurement the client should get doubles and not strings which this is currently possible. Based on the type the client can also display different things for the observations, something like: OM_Measurement = graph, OM_ThruthObservation = On/off button, it should not have to try to cast strings to a double or integer to feed a graph when integers or doubles are expected.

**Comment by bertt** [comment]
we will not implement this now, not in specs
