### ISSUE TITLE
Create benchmark test

### ISSUE THREAD

**Issue by tebben** [gost/server#55]

**Comment by bertt** [comment]
First we need to define some minimal SensorThings benchmark test.

. Define Pre test requests (setup the database + initial filling)
. Define  test requests
. Define benchmark statistics (like request per second)

ideally also define hardware for server (could be added later on)

**Comment by bertt** [comment]
minimal test scenario: 
. Pre test: Create 1 datastream + 1 observation
. Test request: Retrieve observation (like http://localhost/v1.0/Observations(0))
. Statistics: Measure RPS

**Comment by bertt** [comment]
another test:
. send a batch of http post to Observations

**Comment by justb4** [comment]
Maybe useful for stress-test, my JMeter-Docker: https://github.com/justb4/docker-jmeter

**Comment by bertt** [comment]
todo for future milestone
