### ISSUE TITLE
Implement spatial OData filters

### ISSUE THREAD

**Issue by bertt** [gost/server#76]

**Comment by bertt** [comment]
quite a list of these functions in the spec:

Geospatial Functions
double geo.distance(Point p0, Point p1)
geo.distance(location, geography'POINT (30 10) ')
double geo.length(LineString p0)
geo.length(geography'LINESTRING (30 10, 10 30, 40 40) ')
bool geo.intersects(Point p0, Polygon p1)
geo.intersects(location, geography'POLYGON ((30 10, 10 20, 20 40, 40 40, 30 10))')

Spatial Relationship Functions
bool st_equals
st_equals(location, geography'POINT (30 10)')
bool st_disjoint
st_disjoint(location, geography'POLYGON ((30 10, 10 20, 20 40, 40 40, 30 10))')
bool st_touches
st_touches(location, geography'LINESTRING (30 10, 10 30, 40 40)')
bool st_within
st_within(location, geography'POLYGON ((30 10, 10 20, 20 40, 40 40, 30 10))')
bool st_overlaps
st_overlaps(location, geography'POLYGON ((30 10, 10 20, 20 40, 40 40, 30 10))')
bool st_crosses
st_crosses(location, geography'LINESTRING (30 10, 10 30, 40 40)')
bool st_intersects
st_intersects(location, geography'LINESTRING (30 10, 10 30, 40 40)')
bool st_contains
st_contains(location, geography'POINT (30 10)')
bool st_relate
st_relate(location, geography'POLYGON ((30 10, 10 20, 20 40, 40 40, 30 10))', 'T********')

**Comment by bertt** [comment]
Usefull sample spatial query to get it started:

Retrieve all Locations within a provided Polygon and expand the Thing entities to retrieve their metadata.

/v1.0/Locations?$expand=Things&$filter=st_within(location, geography'POLYGON ((-79.39 43.651,-79.371 43.651,-79.371 43.641,-79.39 43.641,-79.39 43.651))')

**Comment by bertt** [comment]
for tests see https://github.com/opengeospatial/ets-sta10/pull/26

**Comment by tebben** [comment]
First step is done: 
http://localhost:8080/v1.0/Locations?$filter=st_within(location,geography'POLYGON((-101 50, -101 51, 101 51, 101 50, -101 50))')
works

**Comment by bertt** [comment]
some error handling to add when geometry is not valid, example

http://localhost:8080/v1.0/Locations?$filter=st_within(location,geography'POLYGON((-101 50, -101 51, 101 51, 101 50, -101 0))')

first point must be same as last point.

current response: http 200 ok 
{
   "value": null
}

expected response: http 400 + error message

**Comment by bertt** [comment]
done

**Comment by Alystrasz** [comment]
Hi,
I'm new to gost environment, so sorry if the question seems stupid. 
Is the `st_within` filter still working ? (I may be using it in a wrong way)

Using Docker image, I'm trying to do this request: `v1.0/Locations?$filter=st_within(location, geography'POLYGON ((-30 -30, 30 -30, 30 30, -30 30, -30 -30))')`, and I'm getting a `502 Bad Gateway` from nginx.

Here's the [complete stacktrace](https://pastebin.com/p2EuD1qZ) from the server.

**Comment by bertt** [comment]
Hi, we can reproduce this error, we'll take a look at it to diagnose. In the meantime you can experiment with st_intersects like v1.0/Locations?$filter=st_intersects(location, geography'POLYGON ((-180 -90, -180 90, 180 90, 180 -90, -180 -90))')

**Comment by tebben** [comment]
Took some more time to fix because of the Locations endpoint only returning max 2 locations when using a filter, should be fixed in 2f952f30b80135a7899379bd2f37b1d82c877971
